### ISSUE TITLE
Create path to abstract pixel sequence

### ISSUE THREAD

**Issue by dayanyrec** [afonsopacifer/css-da-vinci#4]
For example:

``` css
.art {
  a = 10px
  rect(a, a)
  box-shadow:
    p(2, 2, a),
    p(3, 3, a),
    p(4, 4, a);
}
```

result in:

``` css
.art {
  a = 10px
  rect(a, a)
  box-shadow:
    path(2, 4, 2, 4, a); //p(x1, y1, x2, y2, a)
}
```
